CREATE TABLE IF NOT EXISTS tp_post
(
post_id INT NOT NULL,
post BLOB,
ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (post_id)
);

CREATE TABLE IF NOT EXISTS tp_person_score
(
post_id INT NOT NULL,
person_id INT NOT NULL,
score DOUBLE NOT NULL,
ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tp_person_post
(
post_id INT NOT NULL,
person_id INT NOT NULL,
ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);